### ISSUE TITLE
KeyError: 'thumbnail'

### ISSUE THREAD

**Issue by bugbounted** [karim23657/AparatUploader#2]
C:\Users\Bugbounted\Desktop\AparatUploader-main>python test.py
Percent complete: 100.0%Traceback (most recent call last):
  File "C:\Users\Bugbounted\Desktop\AparatUploader-main\test.py", line 8, in <module>
    ap.upload(
  File "C:\Users\Bugbounted\Desktop\AparatUploader-main\aparat.py", line 259, in upload
    if kwargs['thumbnail'] :
       ~~~~~~^^^^^^^^^^^^^
KeyError: 'thumbnail'

**Comment by karim23657** [comment]
@bugbounted , THANK YOU. Solved, use this new version.
